"""
Django settings for isfdb_site project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Real value is set in local_settings.py (not committed to git)
SECRET_KEY = 'replace-me-in-local-settings'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# On HTTPS deployments Django 4.0+ requires CSRF_TRUSTED_ORIGINS to include
# the full scheme+domain (e.g. ['https://www.sfinfo.org', 'https://sfinfo.org']).
# Override this in local_settings.py on the production server.
CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'anymail',
    'magazine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'isfdb_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'isfdb_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Real database credentials are set in local_settings.py (not committed to git)
DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'isfdb',
        'USER': '',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            # ISFDB stores dates as YYYY-MM-00 (day=0). Exclude NO_ZERO_IN_DATE
            # and NO_ZERO_DATE from the session SQL mode so MySQL doesn't raise
            # errors when scanning those rows.
            'sql_mode': 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL          = '/accounts/login/'
LOGIN_REDIRECT_URL = '/collection/'
LOGOUT_REDIRECT_URL = '/'

# Update this when loading a new ISFDB database snapshot.
ISFDB_SNAPSHOT_DATE = "early February 2026"

# These values will change every time we install a new version of
# the ISFDB database.
# Run genstats.py in the mycode directory to generate new assignment
# statements. genstats.py will output the assignment statements to
# setstats.py in the mycode directory.
# These values are referenced on the about page.
ABOUT_STATS = {"authors_with_works": "294203",
"total_titles": "2467006",
"novels": "265751",
"short_fiction": "724409",
"collections": "36103",
"anthologies": "28352",
"nonfiction": "19096",
"series_count": "57353",
"magazine_issues": "82591",
"distinct_magazines": "7831",
"book_pubs": "845841",
"publishers": "41740",
"pubs_with_images": "833469",
"wikipedia_titles": "15876",
"award_types": "120",
"total_awards": "78540",
"awarded_titles": "41933",
}

# Email — uses Resend HTTP API (not SMTP) to avoid port 587 blocks.
# Set RESEND_API_KEY in local_settings.py on production.
RESEND_API_KEY      = ''
DEFAULT_FROM_EMAIL  = 'ISFDB Explorer <noreply@sfinfo.org>'
CONTACT_RECIPIENT   = 'bruce.watkins.1947@gmail.com'

# Machine-specific overrides (secrets, DEBUG, ALLOWED_HOSTS, DATABASES).
# This file is gitignored — create it on each machine separately.
try:
    from .local_settings import *  # noqa: F401, F403
except ImportError:
    pass
