from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("search/", views.combined_search, name="combined_search"),
    path("issues/", views.search, name="search"),
    path("authors/", views.author_list, name="author_list"),
    path("issue/<int:pub_id>/", views.issue_detail, name="issue_detail"),
    path("author/", views.author_search, name="author_search"),
    path("author/<int:author_id>/", views.author_detail, name="author_detail"),
    path("author/<int:author_id>/books/", views.author_books, name="author_books"),
    path("author/<int:author_id>/works/", views.author_works, name="author_works"),
    path("titles/", views.title_search, name="title_search"),
    path("book/<int:title_id>/", views.book_detail, name="book_detail"),
    path("story/<int:title_id>/", views.story_detail, name="story_detail"),
    path("magazines/", views.magazine_list, name="magazine_list"),
    path("magazines/group/<str:group_slug>/", views.magazine_group, name="magazine_group"),
    path("magazines/browse/", views.magazine_issues_by_name, name="magazine_issues_by_name"),
    path("magazines/<str:mag_code>/", views.magazine_issues, name="magazine_issues"),
    path("random/<str:kind>/", views.random_item, name="random_item"),
    path("awards/", views.award_list, name="award_list"),
    path("new-awards/", views.new_award_list, name="new_award_list"),
    path("awards/<int:award_type_id>/", views.award_detail, name="award_detail"),
    path("series/", views.series_list, name="series_list"),
    path("series/author/<int:author_id>/", views.series_by_author, name="series_by_author"),
    path("series/<int:series_id>/", views.series_detail, name="series_detail"),
    path("pubseries/<int:pub_series_id>/", views.pub_series_detail, name="pub_series_detail"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
]
